### ISSUE TITLE
Replace bjeavons/zxcvbn-php with mkopinsky/zxcvbn-php

### ISSUE THREAD

**Issue by DevLazio** [olssonm/l5-zxcvbn#12]
As discussed in this thread https://github.com/bjeavons/zxcvbn-php/issues/15 there is a discrepancy between bjeavons/zxcvbn-php and the upstream JS version. 
The mkopinsky/zxcvbn-php fork fixes these issues and should probably be used instead of bjeavons/zxcvbn-php.

**Comment by olssonm** [comment]
Thanks, I've missed that discussion. Will look into it ASAP!

**Comment by olssonm** [comment]
Thanks for pointing this out, a new version (v4.0) is now released: https://github.com/olssonm/l5-zxcvbn/releases/tag/v4.0
